# Generated by Django 4.2.2 on 2023-06-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=200, null=True)),
                ('StartTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
                ('Description', models.TextField(blank=True)),
                ('IsAllDay', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Name', max_length=200)),
                ('Color', models.CharField(default='#000000', max_length=7)),
            ],
        ),
    ]
